### ISSUE TITLE
req support ipv6

### ISSUE THREAD

**Issue by alsyundawy** [ngandrass/ufw-ipset-blocklist-autoupdate#1]
as title, my server have dual stack ipv4 & ipv6 then ufw have too

can you make support ipv6?
i wanna put dropv6 spamhaus

**Comment by ngandrass** [comment]
Should be possible. I would need to adjust the script to also accept valid IPv6 addresses and store them into a separate ipset. This would then need to be loaded into `ip6tables` in addition to the IPv4 set for `iptables`.

I'll try to take a closer look at it later today and reach back to you no later than Sunday :)

**Comment by ngandrass** [comment]
And here we are! I added support for IPv6 blocklists to the script. You can find it on the `feature/ipv6-support` branch: https://github.com/ngandrass/ufw-ipset-blocklist-autoupdate/tree/feature/ipv6-support

You can now freely mix both IPv4 and IPv6 lists. Example of using both Spamhaus DROP and Spamhaus DROPv6: `./update-ip-blocklists.sh -l "spamhaus https://www.spamhaus.org/drop/drop.txt" -l "spamhaus6 https://www.spamhaus.org/drop/dropv6.txt"`

**Make sure to execute ./setup-ufw.sh and select IPv6 support after pulling the new version!!**

Please give it a try. If everything works fine I'll merge it into `master` :) Thanks!

**Comment by alsyundawy** [comment]
wow thx for support & hard work . Appreciate

**Comment by ngandrass** [comment]
Does the IPv6 support work for you?

**Comment by ngandrass** [comment]
IPv6 support is now fully available with the [v1.1.0 Release](https://github.com/ngandrass/ufw-ipset-blocklist-autoupdate/releases/tag/v1.1.0) :tada:
