### ISSUE TITLE
ask, support other source list too?

### ISSUE THREAD

**Issue by alsyundawy** [ngandrass/ufw-ipset-blocklist-autoupdate#2]
as title, i have source list to make block using ufw. can you support it ?

here 

DSHIELD https://www.dshield.org/block.txt

HONEYPOT https://www.projecthoneypot.org/list_of_ips.php?t=d&rss=1

CIARMY http://www.ciarmy.com/list/ci-badguys.txt

BFB http://danger.rulez.sk/projects/bruteforceblocker/blist.php

BDEALL http://lists.blocklist.de/lists/all.txt

GREENSNOW https://blocklist.greensnow.co/greensnow.txt

binarydefense hack https://www.binarydefense.com/banlist.txt

MALWARE1 https://iplists.firehol.org/files/urlvir.ipset

MALWARE2 https://iplists.firehol.org/files/malwaredomainlist.ipset

MALWARE3 https://iplists.firehol.org/files/malc0de.ipset

abuse.ch https://feodotracker.abuse.ch/downloads/ipblocklist_aggressive.txt

abuse.ch https://feodotracker.abuse.ch/downloads/ipblocklist_recommended.txt

**Comment by ngandrass** [comment]
Currently, all lists are stripped of comments (everything after `#` and `;`) before each line is scanned for valid IPv4 adresses, which are then imported into the ipset. This means that the following blocklists you mentioned should work out of the box:

> CIARMY http://www.ciarmy.com/list/ci-badguys.txt
> 
> BFB http://danger.rulez.sk/projects/bruteforceblocker/blist.php
> 
> BDEALL http://lists.blocklist.de/lists/all.txt
> 
> GREENSNOW https://blocklist.greensnow.co/greensnow.txt
> 
> binarydefensehack https://www.binarydefense.com/banlist.txt
> 
> MALWARE1 https://iplists.firehol.org/files/urlvir.ipset
> 
> MALWARE2 https://iplists.firehol.org/files/malwaredomainlist.ipset
> 
> MALWARE3 https://iplists.firehol.org/files/malc0de.ipset
> 
> abuse.ch https://feodotracker.abuse.ch/downloads/ipblocklist_aggressive.txt
> 
> abuse.ch https://feodotracker.abuse.ch/downloads/ipblocklist_recommended.txt

The only lists that do not follow this format are:

> DSHIELD https://www.dshield.org/block.txt

> HONEYPOT https://www.projecthoneypot.org/list_of_ips.php?t=d&rss=1

We could theoretically provide custom parsing rules for those two lists but in my opinion using all the above lists should be more than sufficient. Would you agree?

**Comment by ngandrass** [comment]
Oh and I forgot to mention, that you can use these alternative/additional source lists by supplying them via the `-l` parameter. See: https://github.com/ngandrass/ufw-ipset-blocklist-autoupdate#supplying-blocklist-sources

**Comment by alsyundawy** [comment]
wow thx for support & hard work . Appreciate

**Comment by alsyundawy** [comment]
> as title, i have source list to make block using ufw. can you support it ?
> 
> here
> 
> DSHIELD https://www.dshield.org/block.txt
> 
> HONEYPOT https://www.projecthoneypot.org/list_of_ips.php?t=d&rss=1
> 
> CIARMY http://www.ciarmy.com/list/ci-badguys.txt
> 
> BFB http://danger.rulez.sk/projects/bruteforceblocker/blist.php
> 
> BDEALL http://lists.blocklist.de/lists/all.txt
> 
> GREENSNOW https://blocklist.greensnow.co/greensnow.txt
> 
> binarydefense hack https://www.binarydefense.com/banlist.txt
> 
> MALWARE1 https://iplists.firehol.org/files/urlvir.ipset
> 
> MALWARE2 https://iplists.firehol.org/files/malwaredomainlist.ipset
> 
> MALWARE3 https://iplists.firehol.org/files/malc0de.ipset
> 
> abuse.ch https://feodotracker.abuse.ch/downloads/ipblocklist_aggressive.txt
> 
> abuse.ch https://feodotracker.abuse.ch/downloads/ipblocklist_recommended.txt

can you add this list wiki?

**Comment by ngandrass** [comment]
I'm sorry but I don't understand your request. Do you want a collection of available blocklists inside the `README.md` file?

**Comment by alsyundawy** [comment]
yes

**Comment by ngandrass** [comment]
Done. I added all compatible and up-to-date blocklists to the [README.md](https://github.com/ngandrass/ufw-ipset-blocklist-autoupdate#available-blocklists).

Lists `MALEWARE1`, `MALEWARE2`, and `MALEWARE3` all received no update since 2020, so I excluded them from the README list.

**Comment by alsyundawy** [comment]
wow thx, appreciate
